[project]
name = "clean_architecture_app"
version = "0.2.0"
description = "A Python backend application demonstrating Clean Architecture and DDD."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "dependency-injector",
    "requests",
    "PyYAML",
    "click",
    "pydantic",
    "aiosqlite",
    "asyncpg",
    "psycopg2-binary",
    "pytest-asyncio",
    "httpx",
    "greenlet",
    "locust",
    "sendgrid",
    "jinja2",
    "alembic",
    "etcd3",
    "protobuf>=3.19.0,<4.0.0",
    "python-dotenv",
    "redis",
    "aiokafka",
    "aiohttp",
    "elasticsearch>=8.0.0,<9.0.0"
]

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["tests"]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "session"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
