[project]
name = "clean_architecture_app"
version = "0.1.0"
description = "A Python backend application demonstrating Clean Architecture and DDD."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "dependency-injector",
    "requests",
    "PyYAML",
    "click",
    "pydantic",
    "aiosqlite",
    "pytest-asyncio",
    "httpx",
    "greenlet"
]

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["tests"]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "session"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
